[general]
extract_c_comment_style = "raw"
show_c_function_prototype = true
output_ignorelist = ["RESTRICT", "NCBRAILLEEGCS", "NCSEGDIGITS"]
use_julia_native_enum_type = true

[codegen]
use_ccall_macro = true

[codegen.macro]
macro_mode = "aggressive"
